In [1]:
import pandas as pd
exam_data = {
    '이름' : ['서준', '우현', '인아'],
    '수학' : [90,80,70],
    '영어' : [98,89,95],
    '음악' : [85,95,100],
    '체육' : [100,90,90],
}

df = pd.DataFrame(exam_data)
df

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  인아  70  95  100   90

In [2]:
df.set_index('이름', inplace=True)
df

    수학  영어   음악   체육
이름
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [4]:
a = df.loc['서준', '음악']
b = df.iloc[0,2]
a, b

(np.int64(85), np.int64(85))

In [7]:
c = df.loc['서준', ['음악', '체육']]
d = df.iloc[0, [2,3]]
e = df.loc['서준','음악':'체육']
f = df.iloc[0, 2:]
c, d, e, f

(음악     85
 체육    100
 Name: 서준, dtype: int64,
 음악     85
 체육    100
 Name: 서준, dtype: int64,
 음악     85
 체육    100
 Name: 서준, dtype: int64,
 음악     85
 체육    100
 Name: 서준, dtype: int64)

In [8]:
g = df.loc[['서준','우현'],['음악','체육']]
h = df.iloc[[0,1],[2,3]]
i = df.loc['서준':'우현','음악':'체육']
j = df.iloc[0:2,2:]
g,h,i,h

(    음악   체육
 이름
 서준  85  100
 우현  95   90,
     음악   체육
 이름
 서준  85  100
 우현  95   90,
     음악   체육
 이름
 서준  85  100
 우현  95   90,
     음악   체육
 이름
 서준  85  100
 우현  95   90)

In [10]:
# 열 추가
df['국어'] = 80
df

    수학  영어   음악   체육  국어
이름
서준  90  98   85  100  80
우현  80  89   95   90  80
인아  70  95  100   90  80

In [12]:
exam_data = {
    '이름' : ['서준', '우현', '인아'],
    '수학' : [90,80,70],
    '영어' : [98,89,95],
    '음악' : [85,95,100],
    '체육' : [100,90,90],
}

df = pd.DataFrame(exam_data)
df

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  인아  70  95  100   90

In [13]:
# 행 추가
df.loc[3] = 0
df

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  인아  70  95  100   90
3   0   0   0    0    0

In [14]:
df.loc[4] = ['동규',90,80,70,60]
df

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  인아  70  95  100   90
3   0   0   0    0    0
4  동규  90  80   70   60

In [15]:
df.loc['행5'] = df.loc[3]
df

    이름  수학  영어   음악   체육
0   서준  90  98   85  100
1   우현  80  89   95   90
2   인아  70  95  100   90
3    0   0   0    0    0
4   동규  90  80   70   60
행5   0   0   0    0    0

In [17]:
exam_data = {
    '이름' : ['서준', '우현', '인아'],
    '수학' : [90,80,70],
    '영어' : [98,89,95],
    '음악' : [85,95,100],
    '체육' : [100,90,90],
}

df = pd.DataFrame(exam_data)
df.set_index('이름', inplace=True)
df

    수학  영어   음악   체육
이름
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [18]:
df.iloc[0][3] = 80
df

C:\Users\pknukdt\AppData\Local\Temp\ipykernel_17996\197081377.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df.iloc[0][3] = 80
C:\Users\pknukdt\AppData\Local\Temp\ipykernel_17996\197081377.py:1: FutureWarning: Series.__setitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To set a value by position, use `ser.iloc[pos] = value`
  df.iloc[0][3] = 80

    수학  영어   음악  체육
이름
서준  90  98   85  80
우현  80  89   95  90
인아  70  95  100  90

In [20]:
df.loc['서준']['체육'] = 90
df

C:\Users\pknukdt\AppData\Local\Temp\ipykernel_17996\982936488.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df.loc['서준']['체육'] = 90

    수학  영어   음악  체육
이름
서준  90  98   85  90
우현  80  89   95  90
인아  70  95  100  90

In [21]:
df.loc['서준','체육'] = 100
df

    수학  영어   음악   체육
이름
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [25]:
df.loc['서준',['음악','체육']] = 50
df

    수학  영어   음악  체육
이름
서준  90  98   50  50
우현  80  89   95  90
인아  70  95  100  90

In [26]:
df.loc['서준', ['음악','체육']] = 100, 60
df

    수학  영어   음악  체육
이름
서준  90  98  100  60
우현  80  89   95  90
인아  70  95  100  90

In [28]:
exam_data = {
    '이름' : ['서준', '우현', '인아'],
    '수학' : [90,80,70],
    '영어' : [98,89,95],
    '음악' : [85,95,100],
    '체육' : [100,90,90],
}

df = pd.DataFrame(exam_data)
df

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  인아  70  95  100   90

In [29]:
df = df.transpose()
df

      0   1    2
이름   서준  우현   인아
수학   90  80   70
영어   98  89   95
음악   85  95  100
체육  100  90   90

In [30]:
df = df.T
df

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  인아  70  95  100   90