In [1]:
import pandas as pd

student1 = pd.Series({'국어':100, '영어':80, '수학':90})
student1

국어    100
영어     80
수학     90
dtype: int64

In [3]:
percentage = student1/200
percentage, type(percentage)

(국어    0.50
 영어    0.40
 수학    0.45
 dtype: float64,
 pandas.core.series.Series)

In [4]:
student2 = pd.Series({'수학':80, '국어':90, '영어':80})
student1, student2

(국어    100
 영어     80
 수학     90
 dtype: int64,
 수학    80
 국어    90
 영어    80
 dtype: int64)

In [7]:
addition = student1 + student2
subtraction = student1 - student2
multiplication = student1 * student2
division = student1 / student2

In [8]:
result = pd.DataFrame([addition, subtraction, multiplication, division],
                      index=['덧셈','뺄셈','곱셈','나눗셈'])
result

              국어        수학      영어
덧셈    190.000000   170.000   160.0
뺄셈     10.000000    10.000     0.0
곱셈   9000.000000  7200.000  6400.0
나눗셈     1.111111     1.125     1.0

In [9]:
import numpy as np
student1 = pd.Series({'국어':np.nan, '영어':80, '수학':90})
student2 = pd.Series({'수학':80, '국어':90})
student1, student2

(국어     NaN
 영어    80.0
 수학    90.0
 dtype: float64,
 수학    80
 국어    90
 dtype: int64)

In [10]:
addition = student1 + student2
subtraction = student1 - student2
multiplication = student1 * student2
division = student1 / student2

In [11]:
result = pd.DataFrame([addition, subtraction, multiplication, division],
                      index=['덧셈','뺄셈','곱셈','나눗셈'])
result

     국어        수학  영어
덧셈  NaN   170.000 NaN
뺄셈  NaN    10.000 NaN
곱셈  NaN  7200.000 NaN
나눗셈 NaN     1.125 NaN

In [14]:
sr_add = student1.add(student2, fill_value=0)
sr_sub = student1.sub(student2, fill_value=0)
sr_mul = student1.mul(student2, fill_value=0)
sr_div = student1.div(student2, fill_value=0)

In [15]:
result = pd.DataFrame([sr_add, sr_sub, sr_mul, sr_div],
                      index=['덧셈','뺄셈','곱셈','나눗셈'])
result

       국어        수학    영어
덧셈   90.0   170.000  80.0
뺄셈  -90.0    10.000  80.0
곱셈    0.0  7200.000   0.0
나눗셈   0.0     1.125   inf

In [16]:
import pandas as pd
import seaborn as sns

titanic = sns.load_dataset('titanic')
df = titanic.loc[:, ['age', 'fare']]
df.head()

    age     fare
0  22.0   7.2500
1  38.0  71.2833
2  26.0   7.9250
3  35.0  53.1000
4  35.0   8.0500

In [17]:
addition = df + 10
addition.head()

    age     fare
0  32.0  17.2500
1  48.0  81.2833
2  36.0  17.9250
3  45.0  63.1000
4  45.0  18.0500

In [18]:
df.tail()

      age   fare
886  27.0  13.00
887  19.0  30.00
888   NaN  23.45
889  26.0  30.00
890  32.0   7.75

In [19]:
addition.tail()

      age   fare
886  37.0  23.00
887  29.0  40.00
888   NaN  33.45
889  36.0  40.00
890  42.0  17.75

In [20]:
subtraction = addition - df
subtraction.head()

    age  fare
0  10.0  10.0
1  10.0  10.0
2  10.0  10.0
3  10.0  10.0
4  10.0  10.0

In [21]:
file_path = './files/read_csv_sample.csv'

df1 = pd.read_csv(file_path)
df1

   c0  c1  c2  c3
0   0   1   4   7
1   1   2   5   8
2   2   3   6   9

In [23]:
df2 = pd.read_csv(file_path, header=None)
df2

    0   1   2   3
0  c0  c1  c2  c3
1   0   1   4   7
2   1   2   5   8
3   2   3   6   9

In [24]:
df3 = pd.read_csv(file_path, index_col=None)
df3

   c0  c1  c2  c3
0   0   1   4   7
1   1   2   5   8
2   2   3   6   9

In [25]:
df4 = pd.read_csv(file_path, index_col='c0')
df4

    c1  c2  c3
c0
0    1   4   7
1    2   5   8
2    3   6   9

In [27]:
import pandas as pd
import requests

url = "https://ko.wikipedia.org/wiki/%EB%8C%80%ED%95%9C%EB%AF%BC%EA%B5%AD%EC%9D%98_%EC%9D%B8%EA%B5%AC"

# 💡 핵심: 봇이 아니라 크롬 브라우저 사용자라고 서버에 속이는 헤더 추가
headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
}

# 1. 페이지 소스코드를 먼저 성공적으로 가져옴
response = requests.get(url, headers=headers)

# 2. 가져온 HTML 텍스트를 판다스 read_html에 전달
table_list = pd.read_html(response.text)

print(f"찾은 표의 개수: {len(table_list)}개")

# 3. 원하는 표 확인 (예: 0번째 표인 '연도별 인구' 가져오기)
df = table_list[0]
df.head()

찾은 표의 개수: 25개

C:\Users\pknukdt\AppData\Local\Temp\ipykernel_19428\243824378.py:15: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  table_list = pd.read_html(response.text)

     연도        인구      ±%
0  1930  13900805       —
1  1940  15627186  +12.4%
2  1949  20166756  +29.0%
3  1960  24989241  +23.9%
4  1970  30882386  +23.6%

In [ ]:
# 지금은 안됨
from bs4 import BeautifulSoup
import requests
import re
import pandas as pd

url = "https://en.wikipedia.org/wiki/List_of_American_exchange-traded_funds"
resp = requests.get(url)
soup = BeautifulSoup(resp.text, 'lxml')
rows = soup.select('div > ul > li')

etfs = {}
for row in rows:

    try:
        eft_name = re.findall('^(.*) \(NYSE', row.text)
        etf_market = re.findall('\((.*)\|', row.text)
        eft_ticker = re.findall('NYSE Arca\|(.*)\)', row.text)

        if (len(eft_ticker) > 0) & (len(etf_market) > 0) & (len(eft_name) > 0):
            etfs[eft_ticker[0]] = [etf_market[0], eft_name[0]]

    except AttributeError as err:
        pass

etfs

{}