In [1]:
import pandas as pd
dict_data = {'c0':[1,2,3],'c1':[4,5,6],'c2':[7,8,9],'c3':[10,11,12],'c4':[13,14,15]}
df = pd.DataFrame(dict_data)
type(df)

pandas.core.frame.DataFrame

In [2]:
df

   c0  c1  c2  c3  c4
0   1   4   7  10  13
1   2   5   8  11  14
2   3   6   9  12  15

In [3]:
df= pd.DataFrame([[15,'남','덕영중'],[17,'여','수리중']],
index=['준서','예은'],
columns=['나이','성별','학교'])

df

    나이 성별   학교
준서  15  남  덕영중
예은  17  여  수리중

In [4]:
df.index

Index(['준서', '예은'], dtype='object')

In [5]:
df.columns

Index(['나이', '성별', '학교'], dtype='object')

In [7]:
df.index=['학생1','학생2']
df.columns=['연령','남녀','소속']
df

     연령 남녀   소속
학생1  15  남  덕영중
학생2  17  여  수리중

In [19]:
df = pd.DataFrame([[15,'남','덕영중'],[17,'여','수리중']],
index=['준서','예은'],
columns=['나이','성별','학교'])
df

    나이 성별   학교
준서  15  남  덕영중
예은  17  여  수리중

In [10]:
df.rename(columns={'나이':'연령', '성별':'남녀', '학교':'소속'}, inplace=True)
df.rename(index={'준서':'학생1', '예은':'학생2'}, inplace=True)
df

     연령 남녀   소속
학생1  15  남  덕영중
학생2  17  여  수리중

In [39]:
exam_data = {'수학' : [90,80,70], '영어':[98,89,95],
'음악' : [85,95,100], '체육':[100,90,90]}

df = pd.DataFrame(exam_data, index=['서준','우현','인아'])
df

    수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [41]:
df2 = df.copy()
df2.drop('우현', inplace=True)
df2

    수학  영어   음악   체육
서준  90  98   85  100
인아  70  95  100   90

In [42]:
df3 = df.copy()
df3.drop(['우현','인아'], axis=0, inplace=True)
df3

    수학  영어  음악   체육
서준  90  98  85  100

In [43]:
exam_data = {'수학' : [90,80,70], '영어':[98,89,95],
'음악' : [85,95,100], '체육':[100,90,90]}

df = pd.DataFrame(exam_data, index=['서준','우현','인아'])
df

    수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [45]:
df4 = df.copy()
df4.drop('수학', axis=1, inplace=True)
df4

    영어   음악   체육
서준  98   85  100
우현  89   95   90
인아  95  100   90

In [46]:
df5 = df.copy()
df5.drop(['영어','음악'], axis=1, inplace=True)
df5

    수학   체육
서준  90  100
우현  80   90
인아  70   90