In [1]:
import pandas as pd
exam_data = {'수학':[90,80,70], '영어':[98,89,95],
'음악':[85,95,100], '체육':[100,90,90]}

df = pd.DataFrame(exam_data, index=['서준', '우현', '인아'])
df

    수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [ ]:
# 행 선택
label1 = df.loc['서준']
position1 = df.iloc[0]
label1, position1

(수학     90
 영어     98
 음악     85
 체육    100
 Name: 서준, dtype: int64,
 수학     90
 영어     98
 음악     85
 체육    100
 Name: 서준, dtype: int64)

In [8]:
label2 = df.loc[['서준', '우현']]
label2

    수학  영어  음악   체육
서준  90  98  85  100
우현  80  89  95   90

In [6]:
position2 = df.iloc[[0,1]]
position2

    수학  영어  음악   체육
서준  90  98  85  100
우현  80  89  95   90

In [9]:
label3 = df.loc['서준':'우현']
label3

    수학  영어  음악   체육
서준  90  98  85  100
우현  80  89  95   90

In [10]:
position3 = df.iloc[0:1]
position3

    수학  영어  음악   체육
서준  90  98  85  100

In [11]:
# 열 선택
exam_data = {
    '이름' : ['서준', '우현', '인아'],
    '수학' : [90,80,70],
    '영어' : [98,89,95],
    '음악' : [85,95,100],
    '체육' : [100,90,90],
}
df = pd.DataFrame(exam_data)
df

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  인아  70  95  100   90

In [15]:
math1 = df['수학']
math1, type(math1)

(0    90
 1    80
 2    70
 Name: 수학, dtype: int64,
 pandas.core.series.Series)

In [16]:
english = df.영어
english, type(english)

(0    98
 1    89
 2    95
 Name: 영어, dtype: int64,
 pandas.core.series.Series)

In [17]:
music_gym = df[['음악', '체육']]
music_gym, type(music_gym)

(    음악   체육
 0   85  100
 1   95   90
 2  100   90,
 pandas.core.frame.DataFrame)

In [19]:
math2 = df[['수학']]
math2, type(math2)

(   수학
 0  90
 1  80
 2  70,
 pandas.core.frame.DataFrame)